apiVersion: kvc.kubeflow.org/v1
kind: VolumeManager
metadata:
  name: kvc-example
  namespace: <insert-namespace-here>
spec:
  volumeConfigs:
    - id: "vol1"
      replicas: 1
      sourceType: "NFS"
      accessMode: "ReadWriteMany"
      capacity: 5Gi
      labels:
        key1: val1
        key2: val2
      options:
        server: <insert-server-ip-here>
        path: <insert-exported-path-here>
    - id: "vol2"
      replicas: 1
      sourceType: "NFS"
      accessMode: "ReadWriteMany"
      capacity: 5Gi
      labels:
        key3: val3
        key4: val4
      options:
        server: <insert-server-ip-here>
        path: <insert-exported-path-here>
