/*
<insert-license-here>
*/
// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/ppkube/vck/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VolumeManagers returns a VolumeManagerInformer.
	VolumeManagers() VolumeManagerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VolumeManagers returns a VolumeManagerInformer.
func (v *version) VolumeManagers() VolumeManagerInformer {
	return &volumeManagerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
