/*
<insert-license-here>
*/
// This file was automatically generated by informer-gen

package v1

import (
	vck_v1 "github.com/ppkube/vck/pkg/apis/vck/v1"
	versioned "github.com/ppkube/vck/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ppkube/vck/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ppkube/vck/pkg/client/listers/vck/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// VolumeManagerInformer provides access to a shared informer and lister for
// VolumeManagers.
type VolumeManagerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VolumeManagerLister
}

type volumeManagerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVolumeManagerInformer constructs a new informer for VolumeManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumeManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumeManagerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVolumeManagerInformer constructs a new informer for VolumeManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumeManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VckV1().VolumeManagers(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VckV1().VolumeManagers(namespace).Watch(options)
			},
		},
		&vck_v1.VolumeManager{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumeManagerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumeManagerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumeManagerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vck_v1.VolumeManager{}, f.defaultInformer)
}

func (f *volumeManagerInformer) Lister() v1.VolumeManagerLister {
	return v1.NewVolumeManagerLister(f.Informer().GetIndexer())
}
