/*
<insert-license-here>
*/
// This file was automatically generated by lister-gen

package v1

// VolumeManagerListerExpansion allows custom methods to be added to
// VolumeManagerLister.
type VolumeManagerListerExpansion interface{}

// VolumeManagerNamespaceListerExpansion allows custom methods to be added to
// VolumeManagerNamespaceLister.
type VolumeManagerNamespaceListerExpansion interface{}
